php_versions: ["7.4", "8.0", "8.1", "8.2", "8.3"]
include:
  - "**/*.php"
  - "**/*.js"
  - "**/*.css"
exclude:
  - "vendor/**"
  - "node_modules/**"
  - ".git/**"
  - "phantom-metadata/**"
checks:
  readme: true
  i18n: true
  security: true
  accessibility: true
  performance: false
ai:
  enabled: true
  mode: deep
  provider: "phantom"
workflow:
  tier_system: true
  metadata_tracking: true
  learning_enabled: true
  copilot_integration: true